name: coverage
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Package with Dev Dependencies
        run: pip install -e .[dev]
      - name: Run tests
        run: nosetests --exclude-dir=tests/custom --with-coverage --cover-package=saucenao
      - name: Update coverage
        run: coveralls